# Generated by Django 5.2.5 on 2025-09-02 22:12

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_1', models.CharField(max_length=20)),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('garantias_firmadas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_prestado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_mensual', models.DecimalField(decimal_places=2, help_text='Porcentaje mensual, ej: 10 para 10%', max_digits=5)),
                ('fecha_prestamo', models.DateField(default=datetime.date.today)),
                ('saldo_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('saldo_interes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('pagado', models.BooleanField(default=False)),
                ('ultima_actualizacion', models.DateField(default=datetime.date.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='core.cliente')),
            ],
            options={
                'ordering': ['fecha_prestamo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abonado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_abono', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.prestamo')),
            ],
        ),
    ]
